### ISSUE TITLE
Ver 2: Support adding global attributes from config files

### ISSUE THREAD

**Issue by hanneskod** [hanneskod/readme-tester#42]
Attributes global to all examples in all input files could be specified in config.

Could for example be used for a lib that always work in the same namespace

```yaml
global_attributes:
    - ReadmeTester\\StartInNamespace('My\\Lib')
```

Or from command line

```shell
readme-tester --global-attribute "ReadmeTester\\StartInNamespace('My\\Lib')"
```

Write attributes to examples using a dedicated `CompilerPass`.

Add docs to `global_attributes.md`. Also add config documentation in `configuration.md`.

**Comment by hanneskod** [comment]
Do we need a command line option for this?

**Comment by hanneskod** [comment]
If we add support for dynamic compiler passes, let's add configuration support for it to!

```yaml
suites:
    default:
        compiler_passes:
            - My\\Custom\\Compiler\\Pass
```

Rename `docs/custom_attributes.md` => `docs/extensions.md` and document compiler passes there..

Or should it be


```yaml
suites:
    default:
        compiler_passes:
            My\\Custom\\Compiler\\Pass:
                arguments: ['foo']
                order: prepend
```
